// AUTH
export const FETCH_AUTH = 'FETCH_AUTH'
export const RECEIVE_AUTH = 'RECEIVE_AUTH'
export const SUCCESS_AUTH = 'SUCCESS_AUTH'
export const FAILED_AUTH = 'FAILED_AUTH'
export const FETCH_LOGOUT_USER = 'FETCH_LOGOUT_USER'
