// USER
export const FETCH_LOGIN_USER = 'FETCH_LOGIN_USER'
export const RECEIVE_LOGIN_USER = 'RECEIVE_LOGIN_USER'
export const FAILED_LOGIN_USER = 'FAILED_LOGIN_USER'
export const FETCH_LOGOUT_USER = 'FETCH_LOGOUT_USER'
export const ERROR_STATUS = 'ERROR_STATUS'
